"use strict";
let EMPRENDEDOR=null,PRODUCTOS=[],CATEGORIAS=[],CANTONES=[],dirty=false,busy=false,objectUrls=[];const dirtyScopes=new Set();
const $=id=>document.getElementById(id), profileForm=$("profileForm"),productForm=$("productForm"),BUCKET_NAME=typeof BUCKET!=="undefined"?BUCKET:"lojanova-imagenes";
const fields={profile:["perfilNombre","perfilEmprendimiento","perfilCanton","perfilAnios","perfilHistoria","perfilTelefono","perfilWhatsapp","perfilCorreo","perfilUbicacion","perfilFacebook","perfilInstagram","perfilFoto"],product:["productoNombre","productoCategoria","productoCanton","productoDescCorta","productoDescLarga","productoProceso","productoIngredientes","productoPresentacion","productoDisponibilidad","productoMercados","productoEtiquetas","productoImagen","productoExportacion","productoArtesanal","productoActivo"]};
function esc(v){return String(v||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function slug(v){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")}
function errorText(error,fallback="No se pudo completar la operación."){const m=String(error?.message||error||"").toLowerCase();if(m.includes("jwt")||m.includes("session"))return"Tu sesión venció. Inicia sesión nuevamente.";if(m.includes("network")||m.includes("fetch"))return"No se pudo conectar con Supabase. Revisa tu conexión e inténtalo otra vez.";if(m.includes("row-level security"))return"No tienes permiso para modificar esta información.";if(m.includes("duplicate"))return"Ya existe un registro con estos datos.";return error?.message||fallback}
function toast(title,message="",type="success"){const el=document.createElement("div");el.className="toast "+type;el.innerHTML=`<i data-lucide="${type==="error"?"circle-alert":"circle-check"}"></i><div><b>${esc(title)}</b><span>${esc(message)}</span></div><button aria-label="Cerrar">×</button>`;el.querySelector("button").onclick=()=>el.remove();$("toastRegion").append(el);lucide.createIcons();setTimeout(()=>el.remove(),5500)}
function saveState(state,text){if(state==="saved"){if(profileForm?.querySelector(".submit-button.loading"))dirtyScopes.delete("profile");if(productForm?.querySelector(".submit-button.loading"))dirtyScopes.delete("product");dirty=dirtyScopes.size>0}if(state==="clean"&&dirtyScopes.size){state="dirty";text="Cambios sin guardar";dirty=true}$("saveIndicator").className="save-indicator state-"+state;$("saveIndicator").querySelector("span").textContent=text}
function setDirty(value=true,scope="general"){if(value)dirtyScopes.add(scope);else dirtyScopes.delete(scope);dirty=dirtyScopes.size>0;saveState(dirty?"dirty":"clean",dirty?"Cambios sin guardar":"Sin cambios")}
function setBusy(form,value){busy=value;const button=form?.querySelector(".submit-button");if(button){button.disabled=value;button.classList.toggle("loading",value)}form?.querySelectorAll("input,select,textarea,button").forEach(el=>{if(el!==button)el.disabled=value})}
function preview(id,url){const el=$(id);if(!url){el.innerHTML='<i data-lucide="image"></i><span>Sin imagen</span>';lucide.createIcons();return}el.innerHTML=`<img src="${esc(url)}" alt="Vista previa">`}
function localPreview(inputId,previewId){$(inputId).addEventListener("change",e=>{const file=e.target.files[0];if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>8*1024*1024){toast("Imagen no válida","Usa JPG, PNG o WEBP de máximo 8 MB.","error");e.target.value="";return}const url=URL.createObjectURL(file);objectUrls.push(url);preview(previewId,url);setDirty(true,inputId.startsWith("perfil")?"profile":"product")})}
async function upload(file,kind){if(!file)return null;const ext=({"image/jpeg":"jpg","image/png":"png","image/webp":"webp"})[file.type];if(!ext||file.size>8*1024*1024)throw new Error("La imagen debe ser JPG, PNG o WEBP y pesar máximo 8 MB.");const path=`productores/${EMPRENDEDOR.auth_user_id}/${kind}-${Date.now()}-${crypto.randomUUID().slice(0,8)}.${ext}`;const {error}=await db.storage.from(BUCKET_NAME).upload(path,file,{cacheControl:"3600",upsert:false,contentType:file.type});if(error)throw error;return db.storage.from(BUCKET_NAME).getPublicUrl(path).data.publicUrl}
function fieldError(id,message){const input=$(id),wrap=input.closest(".field");wrap.classList.toggle("invalid",!!message);const em=wrap.querySelector("em");if(em)em.textContent=message||"";if(message&&!document.activeElement?.closest(".invalid"))input.focus()}
function validProfile(){let ok=true;[["perfilNombre","Escribe tu nombre."],["perfilEmprendimiento","Escribe el nombre del emprendimiento."]].forEach(([id,m])=>{const bad=!$(id).value.trim();fieldError(id,bad?m:"");ok=ok&&!bad});const years=$("perfilAnios").value;if(years&&(Number(years)<0||Number(years)>100)){fieldError("perfilAnios","Ingresa un valor entre 0 y 100.");ok=false}else fieldError("perfilAnios","");const wa=$("perfilWhatsapp").value.trim();if(wa&&!/^\d{8,15}$/.test(wa)){fieldError("perfilWhatsapp","Usa entre 8 y 15 números, sin + ni espacios.");ok=false}else fieldError("perfilWhatsapp","");["perfilFacebook","perfilInstagram"].forEach(id=>{const v=$(id).value.trim();let bad=false;try{if(v)new URL(v)}catch{bad=true}fieldError(id,bad?"Escribe una URL completa que empiece con https://":"");ok=ok&&!bad});const email=$("perfilCorreo");fieldError("perfilCorreo",email.value&&!email.validity.valid?"Escribe un correo válido.":"");return ok&&(!email.value||email.validity.valid)}
function validProduct(){let ok=true;[["productoNombre","Escribe el nombre del producto."],["productoCategoria","Selecciona una categoría."],["productoCanton","Selecciona un cantón."]].forEach(([id,m])=>{const bad=!$(id).value;fieldError(id,bad?m:"");ok=ok&&!bad});return ok}
async function sessionGuard(){const {data:{session},error}=await db.auth.getSession();if(error||!session){location.replace("login.html?sesion=vencida");return false}const [{data:admin},{data:producer,error:producerError}]=await Promise.all([db.from("admins").select("id").eq("id",session.user.id).maybeSingle(),db.from("emprendedores").select("*, cantones(nombre)").eq("auth_user_id",session.user.id).maybeSingle()]);if(admin){await db.auth.signOut();location.replace("admin/index.html");return false}if(producerError||!producer){await db.auth.signOut();location.replace("login.html?perfil=no-encontrado");return false}EMPRENDEDOR=producer;return true}
async function loadLists(){const [ca,co]=await Promise.all([db.from("categorias").select("id,nombre").order("orden"),db.from("cantones").select("id,nombre").order("orden")]);if(ca.error||co.error)throw ca.error||co.error;CATEGORIAS=ca.data||[];CANTONES=co.data||[];const opts=a=>'<option value="">Selecciona…</option>'+a.map(x=>`<option value="${esc(x.id)}">${esc(x.nombre)}</option>`).join("");$("productoCategoria").innerHTML=opts(CATEGORIAS);$("productoCanton").innerHTML=opts(CANTONES);$("perfilCanton").innerHTML=opts(CANTONES)}
function paintProfile(){const p=EMPRENDEDOR,map={perfilNombre:"nombre",perfilEmprendimiento:"emprendimiento",perfilCanton:"canton_id",perfilAnios:"anios_experiencia",perfilHistoria:"historia",perfilTelefono:"telefono",perfilWhatsapp:"whatsapp",perfilCorreo:"correo",perfilUbicacion:"ubicacion",perfilFacebook:"facebook",perfilInstagram:"instagram",perfilFoto:"foto_url"};Object.entries(map).forEach(([id,key])=>$(id).value=p[key]??"");$("producerName").textContent=p.nombre||"Productor";$("producerBusiness").textContent=p.emprendimiento||"Emprendimiento";$("welcomeName").textContent=(p.nombre||"productor").split(" ")[0];$("producerAvatar").textContent=(p.emprendimiento||p.nombre||"L").charAt(0).toUpperCase();preview("perfilFotoPreview",p.foto_url);count("perfilHistoria","perfilHistoriaCount",1200);const complete=["nombre","emprendimiento","canton_id","historia","telefono","whatsapp","correo","ubicacion","foto_url"].filter(k=>p[k]).length;$("kpiCompletitud").textContent=Math.round(complete/9*100)+"%";const state=p.estado||"pendiente";if(state!=="aprobado"){$("estadoBox").hidden=false;$("estadoBox").textContent=state==="rechazado"?"Tu cuenta no fue aprobada. Contacta a la Prefectura de Loja para revisar el caso.":"Tu cuenta está en revisión. Puedes completar el perfil y registrar productos; se publicarán después de la aprobación."}}
async function loadProducts(){const {data,error}=await db.from("productos").select("*, categorias(nombre), cantones(nombre)").eq("emprendedor_id",EMPRENDEDOR.id).order("created_at",{ascending:false});$("productsSkeleton").hidden=true;if(error){toast("No se cargaron los productos",errorText(error),"error");PRODUCTOS=[]}else PRODUCTOS=data||[];$("kpiProductos").textContent=PRODUCTOS.length;$("kpiPublicados").textContent=PRODUCTOS.filter(p=>p.activo).length;renderProducts()}
function renderProducts(){const empty=!PRODUCTOS.length;$("productsEmpty").hidden=!empty;$("productCards").hidden=empty;if(empty)return;$("productCards").innerHTML=PRODUCTOS.map(p=>`<article class="product-card">${p.imagen_principal_url?`<img src="${esc(p.imagen_principal_url)}" alt="">`:'<div class="product-placeholder"><i data-lucide="image"></i></div>'}<div><h3>${esc(p.nombre)} <span class="pill ${p.activo?"on":""}">${p.activo?"Publicado":"Borrador"}</span></h3><p>${esc(p.categorias?.nombre||"Sin categoría")} · ${esc(p.cantones?.nombre||"Sin cantón")}</p></div><div class="product-actions"><button class="btn btn-outline" data-edit="${esc(p.id)}"><i data-lucide="pencil"></i> Editar</button><button class="btn btn-danger" data-delete="${esc(p.id)}"><i data-lucide="trash-2"></i> Eliminar</button></div></article>`).join("");lucide.createIcons()}
function count(inputId,countId,max){$(countId).textContent=`${$(inputId).value.length}/${max}`}
function resetProduct(){productForm.reset();$("productoId").value="";$("productoImagen").value="";$("productoImagenArchivo").value="";$("productoActivo").checked=true;preview("productoImagenPreview","");$("productFormTitle").textContent="Nuevo producto";productForm.querySelectorAll(".invalid").forEach(x=>x.classList.remove("invalid"));count("productoDescCorta","productoDescCortaCount",160)}
function openProduct(id){resetProduct();const p=PRODUCTOS.find(x=>x.id===id);if(p){$("productFormTitle").textContent="Editar producto";const map={productoId:"id",productoNombre:"nombre",productoCategoria:"categoria_id",productoCanton:"canton_id",productoDescCorta:"descripcion_corta",productoDescLarga:"descripcion_larga",productoProceso:"proceso_elaboracion",productoIngredientes:"ingredientes",productoPresentacion:"presentacion",productoDisponibilidad:"disponibilidad",productoMercados:"mercados",productoImagen:"imagen_principal_url"};Object.entries(map).forEach(([a,b])=>$(a).value=p[b]??"");$("productoEtiquetas").value=(p.etiquetas||[]).join(", ");$("productoExportacion").checked=!!p.es_exportacion;$("productoArtesanal").checked=!!p.es_artesanal;$("productoActivo").checked=!!p.activo;preview("productoImagenPreview",p.imagen_principal_url);count("productoDescCorta","productoDescCortaCount",160)}$("productFormPanel").hidden=false;$("productFormPanel").scrollIntoView({behavior:"smooth"});lucide.createIcons()}
function confirmDelete(product){return new Promise(resolve=>{const dialog=$("confirmDialog");$("confirmMessage").textContent=`Se eliminará “${product.nombre}” permanentemente. Esta acción no se puede deshacer.`;dialog.hidden=false;const done=value=>{dialog.hidden=true;$("confirmAccept").onclick=null;$("confirmCancel").onclick=null;resolve(value)};$("confirmAccept").onclick=()=>done(true);$("confirmCancel").onclick=()=>done(false)})}
profileForm.addEventListener("submit",async e=>{e.preventDefault();if(busy||!validProfile()){toast("Revisa el formulario","Corrige los campos marcados antes de guardar.","error");return}setBusy(profileForm,true);saveState("saving","Guardando…");try{const file=$("perfilFotoArchivo").files[0];if(file)$("perfilFoto").value=await upload(file,"perfil");const payload={nombre:$("perfilNombre").value.trim(),emprendimiento:$("perfilEmprendimiento").value.trim(),canton_id:$("perfilCanton").value||null,anios_experiencia:$("perfilAnios").value?Number($("perfilAnios").value):null,historia:$("perfilHistoria").value.trim(),telefono:$("perfilTelefono").value.trim(),whatsapp:$("perfilWhatsapp").value.trim(),correo:$("perfilCorreo").value.trim(),ubicacion:$("perfilUbicacion").value.trim(),facebook:$("perfilFacebook").value.trim(),instagram:$("perfilInstagram").value.trim(),foto_url:$("perfilFoto").value.trim()};const {data,error}=await db.from("emprendedores").update(payload).eq("id",EMPRENDEDOR.id).select("*, cantones(nombre)").single();if(error)throw error;EMPRENDEDOR=data;$("perfilFotoArchivo").value="";paintProfile();dirty=false;saveState("saved","Guardado");$("profileLastSaved").textContent="Guardado a las "+new Date().toLocaleTimeString("es-EC",{hour:"2-digit",minute:"2-digit"});toast("Perfil guardado","Tus cambios ya están en Supabase.");setTimeout(()=>{if(!dirty)saveState("clean","Sin cambios")},2500)}catch(error){saveState("error","Error al guardar");toast("No se guardó el perfil",errorText(error),"error")}finally{setBusy(profileForm,false)}})
productForm.addEventListener("submit",async e=>{e.preventDefault();if(busy||!validProduct()){toast("Revisa el formulario","Completa nombre, categoría y cantón.","error");return}setBusy(productForm,true);saveState("saving","Guardando…");try{const file=$("productoImagenArchivo").files[0];if(file)$("productoImagen").value=await upload(file,"producto");const id=$("productoId").value,nombre=$("productoNombre").value.trim(),payload={nombre,categoria_id:$("productoCategoria").value,canton_id:$("productoCanton").value,emprendedor_id:EMPRENDEDOR.id,descripcion_corta:$("productoDescCorta").value.trim(),descripcion_larga:$("productoDescLarga").value.trim(),proceso_elaboracion:$("productoProceso").value.trim(),ingredientes:$("productoIngredientes").value.trim(),presentacion:$("productoPresentacion").value.trim(),disponibilidad:$("productoDisponibilidad").value.trim(),mercados:$("productoMercados").value.trim(),etiquetas:$("productoEtiquetas").value.split(",").map(x=>x.trim()).filter(Boolean),imagen_principal_url:$("productoImagen").value.trim(),es_artesanal:$("productoArtesanal").checked,es_exportacion:$("productoExportacion").checked,activo:$("productoActivo").checked};if(!id)payload.slug=slug(nombre)+"-"+Date.now().toString(36);const query=id?db.from("productos").update(payload).eq("id",id).eq("emprendedor_id",EMPRENDEDOR.id):db.from("productos").insert(payload);const {error}=await query;if(error)throw error;await loadProducts();$("productFormPanel").hidden=true;resetProduct();saveState("saved","Guardado");toast("Producto guardado","El catálogo quedó actualizado.");setTimeout(()=>saveState("clean","Sin cambios"),2500)}catch(error){saveState("error","Error al guardar");toast("No se guardó el producto",errorText(error),"error")}finally{setBusy(productForm,false)}})
document.addEventListener("input",e=>{const form=e.target.closest("#profileForm,#productForm");if(form)setDirty(true,form.id==="profileForm"?"profile":"product");if(e.target.id==="perfilHistoria")count("perfilHistoria","perfilHistoriaCount",1200);if(e.target.id==="productoDescCorta")count("productoDescCorta","productoDescCortaCount",160)});
$("productCards").addEventListener("click",async e=>{const edit=e.target.closest("[data-edit]"),del=e.target.closest("[data-delete]");if(edit)openProduct(edit.dataset.edit);if(del){const p=PRODUCTOS.find(x=>x.id===del.dataset.delete);if(!p||!await confirmDelete(p))return;del.disabled=true;try{const {error}=await db.from("productos").delete().eq("id",p.id).eq("emprendedor_id",EMPRENDEDOR.id);if(error)throw error;await loadProducts();toast("Producto eliminado","El producto ya no está en tu catálogo.")}catch(error){toast("No se pudo eliminar",errorText(error),"error")}finally{del.disabled=false}}});
function closeEditor(){if(dirtyScopes.has("product")&&!confirm("Hay cambios del producto sin guardar. ¿Quieres cerrar el editor?"))return;$("productFormPanel").hidden=true;resetProduct();setDirty(false,"product")}
$("btnNuevoProducto").onclick=()=>openProduct();document.querySelector("[data-new-product]").onclick=()=>openProduct();$("btnCancelarProducto").onclick=closeEditor;$("btnCerrarProducto").onclick=closeEditor;
localPreview("perfilFotoArchivo","perfilFotoPreview");localPreview("productoImagenArchivo","productoImagenPreview");
function toggleMenu(open){$("sidebar").classList.toggle("open",open);$("sidebarBackdrop").classList.toggle("open",open)}$("mobileToggle").onclick=()=>toggleMenu(!$("sidebar").classList.contains("open"));$("sidebarBackdrop").onclick=()=>toggleMenu(false);
$("btnLogout").onclick=async()=>{if(dirty&&!confirm("Tienes cambios sin guardar. ¿Cerrar sesión de todos modos?"))return;$("btnLogout").disabled=true;await db.auth.signOut();location.replace("login.html")};
window.addEventListener("beforeunload",e=>{if(dirty){e.preventDefault();e.returnValue=""}});db.auth.onAuthStateChange((event,session)=>{if(event==="SIGNED_OUT"||(!session&&event!=="INITIAL_SESSION"))location.replace("login.html")});
(async()=>{try{lucide.createIcons();if(!await sessionGuard())return;await loadLists();paintProfile();await loadProducts();$("producerApp").hidden=false;$("appLoader").remove();setDirty(false);lucide.createIcons()}catch(error){$("appLoader").innerHTML='<p>No pudimos preparar el panel.</p><button class="btn btn-primary" onclick="location.reload()">Reintentar</button>';toast("Error al cargar",errorText(error),"error")}})();
